//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWPF.DataApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user50Entities : DbContext
    {
        public user50Entities()
            : base("name=user50Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order1> Order1 { get; set; }
        public virtual DbSet<Product1> Product1 { get; set; }
        public virtual DbSet<Role1> Role1 { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
    }
}
